// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  apiUrl:'http://www.omdbapi.com/',
  apiKey:'5cc5133f',
  version: env.npm_package_version,
//  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR']
};
